title: Aakash Solanki
url: https://aakashsolanki.net
baseurl: ""
author: Aakash Solanki
logo: /assets/img/logo.jpg
orcid: https://orcid.org/0000-0002-4879-6998
permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  path: feed.xml
